local gears = require('gears');
local beautiful = require('beautiful');
local xrdb = beautiful.xresources.get_current_theme();

return {
  global = {
    f = xrdb.color7.."73",
    f2 = xrdb.color7.."80",
    t = "#00000000",
    b = "#000000",
    m = 10,
    r = 7,
    o = 0.35,
    user = gears.filesystem.get_configuration_dir()..'/helpers/andy-emoji-linicorn.png',
  },
  fonts = {
    is = "MaterialDesignIconsDesktop 12",
    im = "MaterialDesignIconsDesktop 14",
    il = "MaterialDesignIconsDesktop 20",
    ts = "SF Pro Rounded 9",
    tm = "SF Pro Rounded 10",
    tl = "SF Pro Rounded 12",
    tsl = "SF Pro Rounded Light 9",
    tml = "SF Pro Rounded Light 10",
    tll = "SF Pro Rounded Light 12",
    tsb = "SF Pro Rounded Semibold 9",
    tmb = "SF Pro Rounded Semibold 10",
    tlb = "SF Pro Rounded Semibold 12",
  },
  topbar = {
    h = 30,
    w = 30,
  },
  tagswitcher= {
    h = 120,
  },
  hub = {
    i = 40,
    w = 800,
    h = 600,
    nw = 260,
  },
  icons = {
    arch = '󰣇',
    power = '󰐥',
    date = '󰸘',
    time = '󰅐',
    vol_mute = '󰝟',
    vol_1 = '󰕿',
    vol_2 = '󰖀',
    vol_3 = '󰕾',
    wifi = '󰖩',
    bt = '󰂯',
    pac = '󰏗',
    mem = '󰍛',
    wifix = '󰖪',
    btx = '󰂲',
    lan = '󰲝',
    lanx = '󰲜',
    note = '󰀠',
    web = '󰖟',
    system = '󰄨',
    display = '󰇄',
    media = '󰝚',
    theme = '󰸌',
  },
  commands = {
    wifiup = 'bash '..gears.filesystem.get_configuration_dir()..'helpers/wifiup.sh',
    lanup = 'bash '..gears.filesystem.get_configuration_dir()..'helpers/lanup.sh',
    btup = 'bash '..gears.filesystem.get_configuration_dir()..'helpers/btup.sh',
    btdevices = 'bash '..gears.filesystem.get_configuration_dir()..'helpers/btdevices.sh',
    btdevice = 'bash '..gears.filesystem.get_configuration_dir()..'helpers/btdevice.sh',
    ismuted = 'bash -c "pamixer --get-mute | diff <(echo \"true\") -"',
    vol = 'bash -c "pamixer --get-volume"',
    ssid = 'iwgetid -r',
  }
};